### PR TITLE
tycho-versions-plugin: Support ci-friendly versions

### LINKED ISSUE #3744: set-version fails to update MANIFEST.MF if CI-firendly versions are in use
# Environment
Tycho 4.0.7
```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 21.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_GE, platform encoding: UTF-8
OS name: "mac os x", version: "12.7.4", arch: "aarch64", family: "mac"
```
 
# Test steps
- Unzip [versionFail.zip](https://github.com/eclipse-tycho/tycho/files/14968232/versionFail.zip)
- Ensure that `mvn clean verify -f versionFail` succeeds
- Run `mvn -f versionFail org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.0.0-SNAPSHOT`. Ensure is succeeds.
- Run `mvn -f versionFail clean verify` again

# Expected result
A build should succeed as no manual changes were applied to the project - `set-version` command was the only actor.

# Actual result
A build fails with:
```
versionFail/META-INF/MANIFEST.MF [5:0]: Unqualified OSGi version 1.0.0.qualifier must match unqualified Maven version 2.0.0-SNAPSHOT for SNAPSHOT builds
```

# Excerpts

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: VersionFail
Bundle-SymbolicName: versionFail
Bundle-Version: 1.0.0.qualifier
Automatic-Module-Name: versionFail
Bundle-RequiredExecutionEnvironment: JavaSE-17
```

	<artifactId>versionFail</artifactId>
	<groupId>com.example</groupId>
	<packaging>eclipse-plugin</packaging>
	<properties>
		<revision>1.0.0-SNAPSHOT</revision>
	</properties>
	<version>${revision}</version>

# Notes
An attempt to use ${revision} in MANIFEST.MF breaks PDE:

    Invalid manifest header Bundle-Version: "${revision}" : invalid version "${revision}": non-numeric "${revision}"

### PR DESCRIPTION
**Pull request by sratz**
In PomFile#getVersion(), resolve properties used in the raw version of the project. This is necessary so that downstream manipulators (MANIFEST.MF, feature.xml, category.xml, ...) can see the actual version and act on it.

Fixes #3744.

### CODE REVIEW

File: tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java [hunk 1]
```diff
@@ -245,4 +276,25 @@ private String getElementValue(String name) {
     public boolean isMutable() {
         return isMutable;
     }
+
+    private static boolean isCiFriendly(String v) {
```
Comment (laeubi) [inline tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java:280]: can we make this a public static  somewhere as it seems to be used in more than one place now in the `PomFile` and `PomManipulator`?

File: tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java [hunk 2]
```diff
@@ -245,4 +276,25 @@ private String getElementValue(String name) {
...
+        return v != null && v.contains("${");
+    }
+
+    private void resolveCiFriendlyVersion() {
```
Comment (laeubi) [inline tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java:284]: can this be made to return the resolved version instead of manipulate the resolved version directly?

File: tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java [hunk 3]
```diff
@@ -158,13 +167,35 @@ public void setParentVersion(String newVersion) {
...
+        this.resolvedVersion = null;
     }
 
     /**
      * Returns the (effective) version of the project.
      */
     public String getVersion() {
-        return version;
+        if (this.resolvedVersion == null) {
+            resolveCiFriendlyVersion();
```
Comment (laeubi) [inline tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java:178]:
```suggestion
            resolvedVersion = resolveCiFriendlyVersion();
```

File: tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java (hunk 1 above)
Comment (laeubi) [reply tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java:280]: should this be deleted now?

File: tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java [hunk 4]
```diff
@@ -158,13 +167,35 @@ public void setParentVersion(String newVersion) {
...
+        return this.resolvedVersion;
+    }
+
+    /**
+     * Returns the list of property names that make up the <code>&lt;version&gt;</code> of the
+     * project.
+     * <p>
+     * If this list is non-empty, the project uses ci-friendly versions.
+     */
+    public List<String> getCiFriendlyVersionPropertyNames() {
```
Comment (laeubi) [inline tycho-versions-plugin/src/main/java/org/eclipse/tycho/versions/pom/PomFile.java:189]: Maybe move to `PomVersionsUtil` and pass the version as a parameter?
```suggestion
    public static List<String> getCiFriendlyVersionPropertyNames(String version) {
```

**Comment by sratz** [comment]
I refactored things a bit more. In fact, the utility is not specific to versions, but just deals with properties in general.

**Review by laeubi — APPROVED** [review]
Looks very good, thank you!

**Comment by HannesWell** [comment]
@sratz is it possible that the back-port of this has broken P2's use of version variables/ci-friendly versions?
https://github.com/eclipse-equinox/p2/blob/65348d689980d1e11708f934f1767f056e62907d/pom.xml#L25-L32

Since Tycho 4.0.9 the `tycho-versions-plugin:set-parent-version` goal cannot set the root version of p2 anymore: `<version>${releaseVersion}${qualifier}</version>`
See https://github.com/eclipse-equinox/p2/actions/runs/11973081501/job/33420895519
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-versions-plugin:4.0.9:set-parent-version (default-cli) on project rt.equinox.p2: Execution default-cli of goal org.eclipse.tycho:tycho-versions-plugin:4.0.9:set-parent-version failed: No group with name {releaseVersion} -> [Help 1]
```
I verified it locally that it works with Tycho 4.0.8 and we had corresponding release preparation PRs for p2 in the past.

**Comment by sratz** [comment]
> @sratz is it possible that the back-port of this has broken P2's use of version variables/ci-friendly versions?

I think it brought to light a hidden problem that already existed before:

`SetVersionMojo` (set-version) is supposed to descend to child modules / projects, while 
`SetParentVersionMojo` (set-parent-version) is not

Is this assumption correct, @laeubi?

`SetParentVersionMojo` inherits from `AbstractChangeMojo` and inherits the same descend-logic. This logic, however, always looks at `getVersion()` of the children.

**Comment by laeubi** [comment]
@sratz thats was at least the idea of it, but we can of course change things if it performs better.

**Comment by sratz** [comment]
@laeubi I am trying to understand the original intention of the `set-parent-version` mojo.

Assuming the following directory structure:
```
pom.xml
    <version>1.0.0</version>

  child1\pom.xml <-- run org.eclipse.tycho:tycho-versions-plugin:set-parent-version -DnewParentVersion=2.0.0 here
      <parent>
          <version>1.0.0</version>
      </parent>
      <version>1.0.0</version>

    child1\child1a\pom.xml
        <parent>
            <version>1.0.0</version>
        </parent>
        <version>1.0.0</version>

    child1\child1b\pom.xml
        <parent>
            <version>1.0.0</version>
        </parent>
        <version>1.0.0</version>

  child2\pom.xml
      <parent>
          <version>1.0.0</version>
      </parent>
      <version>1.0.0</version>

    child2\child2a\pom.xml
        <parent>
            <version>1.0.0</version>
        </parent>
        <version>1.0.0</version>

    child2\child1b\pom.xml
        <parent>
            <version>1.0.0</version>
        </parent>
        <version>1.0.0</version>
```

The result is:
```
pom.xml
    <version>2.0.0</version>

  child1\pom.xml
      <parent>
          <version>2.0.0</version>
      </parent>
      <version>2.0.0</version>

    child1\child1a\pom.xml
        <parent>
            <version>2.0.0</version>
        </parent>
        <version>2.0.0</version>

    child1\child1b\pom.xml
        <parent>
            <version>2.0.0</version>
        </parent>
        <version>2.0.0</version>

  child2\pom.xml
      <parent>
          <version>2.0.0</version>
      </parent>
      <version>2.0.0</version>

    child2\child2a\pom.xml
        <parent>
            <version>2.0.0</version>
        </parent>
        <version>2.0.0</version>

    child2\child1b\pom.xml
        <parent>
            <version>2.0.0</version>
        </parent>
        <version>2.0.0</version>
```

Versions have essentially changed *everywhere*, even *outside* of the current directory.

Is this really the intention of the mojo?

**Comment by sratz** [comment]
The actual regression and IllegalArgumentException is fixed with #4453. Although I still think the `set-parent-version` mojo is strange and not really doing what it was intended for :)
